# Generated by Django 2.2.24 on 2021-08-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channel_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='api_key',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_api_key.APIKey'),
        ),
    ]
